### ISSUE TITLE
Rules-Folder- Folder selection stuck on "Desktop", unable to click into or expand

### ISSUE THREAD

**Issue by shanezuspan** [Stonepaw/comicrack-library-organizer#10]
Will try to drag and drop but figured to ask in case anyone has run into this as well...
![2023-03-12_12-04-28](https://user-images.githubusercontent.com/55251478/224566977-753246a6-ff3a-4c76-855d-9aa7d9248d38.png)

**Comment by Stonepaw** [comment]
If you are using windows 11 I believe this is an issue when OneDrive is installed. ComicRack has a similar issue I think

**Comment by shanezuspan** [comment]
Turned off "run as admin"
