### ISSUE TITLE
Different year formats for completed/uncompleted/short series?

### ISSUE THREAD

**Issue by Cantello** [Stonepaw/comicrack-library-organizer#14]
I'd like to organise my (small) library a bit better and intended to add the running years for each series but as I have many Graphic Novels and mini-series, I would like to have three different date formats:

- for a completed, longer-running series: (StartYear-EndYear)
- for a completed mini-series/GN: (StartYear)
- for an ongoing longer-running series: (StartYear-) (to differentiate between this and a mini series)

Is this possible? I currently have this:
`\{ <language>}\{ <seriesgroup>}\{<series>}{ - V<volume0>} { ({<startyear>}<!startyear({<EndYear>})>-{<EndYear>})}{ ({<startyear>}<?startyear({<EndYear>})>)}`

but I cannot figure out how to have the trailing dash insererted depending on the completeness status.
Any ideas?

**Comment by Stonepaw** [comment]
Generally I would recommend using multiple profiles with rules to match mini-series, completed series, or ongoing series.

I'll see if I can think of a way to do it with a conditional though.

**Comment by Cantello** [comment]
I have now set up two different profiles (separate folder formats as per a rule on `Series Complete`), which work well, but can the profile also be selected by a rule? As it is now, LO asks me, which profile to use.

_edit_: Ok, I was too blind to see the `add` button on the profile selection where I can add/move the additional profiles. I  have now put the one for completed series at the bottom and ongoing series above and so far it is working well.
