### ISSUE TITLE
Feature request: "copy-only" folders

### ISSUE THREAD

**Issue by chowbok** [Stonepaw/comicrack-library-organizer#2]
Would it be possible to add under "folder rules" a rule to add folders where files are only copied from but not moved? In other words, I'd like all my files to be moved to directory A, _except_ the ones in directory B, which should only be copied.

Thanks for this, by the way. It's really useful.

**Comment by Stonepaw** [comment]
I believe this can be done now with metadata rules:

1. Create a profile with the mode as move and add folder rule
> Do not move books if they are in `directory B`
2. Duplicate the profile and change mode to copy. remove the folder rule and add a metadata rule:
> Only move books that match All of the follow rules: File Path contains `full/path/of/directory B`
