### ISSUE TITLE
UX issue

### ISSUE THREAD

**Issue by siddjellali** [Stonepaw/comicrack-library-organizer#3]
Hi, 

I'm running on Win10 with a large screen 3840x2400 and i have the design issue.
Could you please provide a patch ? Many thanks.

![image](https://user-images.githubusercontent.com/3965823/130762494-a42923d5-3d1e-4418-9922-ca9771314ab7.png)

**Comment by Stonepaw** [comment]
ComicRack must be run in HDPI compatibility mode to fix this. [See here for details](https://www.reddit.com/r/comicrackusers/comments/nvnunv/comment/h14h2gq).
