### ISSUE TITLE
unable to move file according to Rules

### ISSUE THREAD

**Issue by Webcr0ler** [Stonepaw/comicrack-library-organizer#5]
Hi,
i've set the metadata rule  : Only move books that match any of the following rules
format contains manga
when i simulate it says "The book qualified under the exclude rules" 
i've tryed with move or not move, genre contains manga, nothing works.

**Comment by Stonepaw** [comment]
I will need some additional information to investigate this.

1. Please export and attach your profiles
2. Please provide a screenshot of the comic details tab for the comic that is failing to match the rules.

**Comment by Webcr0ler** [comment]
Finaly i get it,
now it works (don't know why), i have to write the words exactly as it have to be (it's case sensitive)
thank you for all your hard work.
