### ISSUE TITLE
Day field missing on copy function

### ISSUE THREAD

**Issue by shanezuspan** [Stonepaw/comicrack-library-organizer#6]
Hi! Anyone know why the published date is losing the "day" field data when copying the file? Set  LO to copy to another folder and add to library. Source published date is complete, but when copies and renames the day field is now blank. 

![2023-03-10_19-49-41](https://user-images.githubusercontent.com/55251478/224463484-6ef85aa0-23da-45d0-9dfe-9c94d7246f22.png)
![2023-03-10_19-51-05](https://user-images.githubusercontent.com/55251478/224463497-a215089e-cb3d-4609-aa13-bdc88066ff98.png)
![2023-03-10_19-52-15](https://user-images.githubusercontent.com/55251478/224463503-1e32cca2-4e0d-4abb-ac57-23ef0811cacd.png)

**Comment by shanezuspan** [comment]
Ok , so I think if I "update files" before running LO it keeps the data... still checking...

**Comment by Stonepaw** [comment]
This is now resolved in [2.1.13](https://github.com/Stonepaw/comicrack-library-organizer/releases/tag/2.1.13)
